let animalData = [];
animalData.push(["Golden jackal","Canis aureus","water",true]);
animalData.push(["Guanaco","Lama guanicoe","air",true]);
animalData.push(["Coot, red-knobbed","Fulica cristata","air",false]);
animalData.push(["Jaguarundi","Felis yagouaroundi","water",true]);
animalData.push(["Steller's sea lion","Eumetopias jubatus","water",false]);
animalData.push(["Green vine snake","Oxybelis fulgidus","land",false]);
animalData.push(["Puku","Kobus vardonii vardoni","land",false]);
animalData.push(["Spotted wood sandpiper","Tringa glareola","water",true]);
animalData.push(["Lizard, blue-tongued","Tiliqua scincoides","land",true]);
animalData.push(["Salmon pink bird eater tarantula","Lasiodora parahybana","land",true]);
animalData.push(["Long-billed cockatoo","Cacatua tenuirostris","land",true]);
animalData.push(["Huron","Galictis vittata","land",false]);
animalData.push(["Otter, oriental short-clawed","Aonyx cinerea","water",false]);
animalData.push(["Brazilian tapir","Tapirus terrestris","air",false]);
animalData.push(["Tortoise, burmese black mountain","Manouria emys","water",true]);
animalData.push(["Little heron","Butorides striatus","land",false]);
animalData.push(["Macaw, blue and yellow","Ara ararauna","land",true]);
animalData.push(["White-throated robin","Irania gutteralis","land",false]);
animalData.push(["Common dolphin","Delphinus delphis","water",true]);
animalData.push(["Reedbuck, bohor","Redunca redunca","water",false]);
animalData.push(["Hyena, spotted","Crocuta crocuta","water",true]);
animalData.push(["Godwit, hudsonian","Limosa haemastica","land",true]);
animalData.push(["Dove, emerald-spotted wood","Turtur chalcospilos","water",true]);
animalData.push(["Swallow (unidentified)","unavailable","air",true]);
animalData.push(["Curve-billed thrasher","Toxostoma curvirostre","air",false]);
animalData.push(["Barbet, crested","Trachyphonus vaillantii","air",false]);
animalData.push(["Bettong, brush-tailed","Bettongia penicillata","land",false]);
animalData.push(["Canadian river otter","Lutra canadensis","water",true]);
animalData.push(["Blue catfish","Ictalurus furcatus","water",false]);
animalData.push(["Emerald green tree boa","Boa caninus","land",false]);
animalData.push(["Booby, blue-faced","Sula dactylatra","water",false]);
animalData.push(["Greater kudu","Tragelaphus strepsiceros","air",true]);
animalData.push(["Long-nosed bandicoot","Perameles nasuta","air",true]);
animalData.push(["Francolin, coqui","Francolinus coqui","water",true]);
animalData.push(["Tyrant flycatcher","Myiarchus tuberculifer","water",true]);
animalData.push(["Stork, white","Ciconia ciconia","air",true]);
animalData.push(["Seal, southern elephant","Mirounga leonina","air",false]);
animalData.push(["Kangaroo, brush-tailed rat","Bettongia penicillata","air",true]);
animalData.push(["Oriental short-clawed otter","Aonyx cinerea","air",false]);
animalData.push(["Grison","Galictis vittata","air",true]);
animalData.push(["Hornbill, yellow-billed","Tockus flavirostris","water",false]);
animalData.push(["Red-billed toucan","Ramphastos tucanus","air",true]);
animalData.push(["Red sheep","Ovis ammon","land",true]);
animalData.push(["Common mynah","Acridotheres tristis","land",false]);
animalData.push(["Agouti","Dasyprocta leporina","water",true]);
animalData.push(["Russian dragonfly","Libellula quadrimaculata","land",true]);
animalData.push(["Blue duck","Hymenolaimus malacorhynchus","air",true]);
animalData.push(["Albatross, waved","Diomedea irrorata","air",false]);
animalData.push(["White-rumped vulture","Gyps bengalensis","air",true]);
animalData.push(["Striped dolphin","Stenella coeruleoalba","land",true]);
animalData.push(["Ass, asiatic wild","Equus hemionus","air",true]);
animalData.push(["South African hedgehog","Erinaceus frontalis","land",false]);
animalData.push(["Monkey, black spider","Ateles paniscus","air",false]);
animalData.push(["Baleen whale","Eubalaena australis","air",true]);
animalData.push(["Masked booby","Sula dactylatra","land",false]);
animalData.push(["Flamingo, lesser","Phoeniconaias minor","land",false]);
animalData.push(["Little brown dove","Streptopelia senegalensis","land",true]);
animalData.push(["Pigeon, feral rock","Columba livia","air",true]);
animalData.push(["Turkey, australian brush","Alectura lathami","land",false]);
animalData.push(["Coqui partridge","Francolinus coqui","water",true]);