const pokemonList = [
    ["Charmander", "Fire", 39, 52, "Scratch", "Ember"],
    ["Squirtle", "Water", 44, 48, "Tackle", "Water Gun"],
    ["Pikachu", "Electric", 35, 55, "Quick Attack", "Thunder Shock"],
    ["Geodude", "Rock", 40, 80, "Tackle", "Rock Throw"],
    ["Bulbasaur", "Leaf", 45, 49, "Tackle", "Vine Whip"],
    ["Vulpix", "Fire", 38, 41, "Quick Attack", "Ember"],
    ["Psyduck", "Water", 50, 52, "Scratch", "Water Gun"],
    ["Magnemite", "Electric", 25, 35, "Tackle", "Thunder Shock"],
    ["Onix", "Rock", 35, 45, "Tackle", "Rock Throw"],
    ["Oddish", "Leaf", 45, 50, "Absorb", "Acid"],
    ["Growlithe", "Fire", 55, 70, "Bite", "Flame Wheel"],
    ["Poliwag", "Water", 40, 50, "Bubble", "Water Gun"],
    ["Voltorb", "Electric", 40, 30, "Tackle", "Spark"],
    ["Rhyhorn", "Rock", 80, 85, "Horn Attack", "Rock Throw"],
    ["Bellsprout", "Leaf", 50, 75, "Vine Whip", "Acid"],
    ["Ponyta", "Fire", 50, 85, "Tackle", "Flame Charge"],
    ["Tentacool", "Water", 40, 40, "Poison Sting", "Water Gun"],
    ["Electabuzz", "Electric", 65, 83, "Quick Attack", "Thunder Punch"],
    ["Kabuto", "Rock", 30, 80, "Scratch", "Rock Throw"],
    ["Exeggcute", "Leaf", 60, 40, "Barrage", "Confusion"],
    ["Magmar", "Fire", 65, 95, "Ember", "Fire Punch"],
    ["Seel", "Water", 65, 45, "Headbutt", "Water Gun"],
    ["Jolteon", "Electric", 65, 110, "Quick Attack", "Thunder Shock"],
    ["Omanyte", "Rock", 35, 40, "Water Gun", "Rock Throw"],
    ["Tangela", "Leaf", 65, 55, "Vine Whip", "Constrict"],
    ["Charmeleon", "Fire", 58, 64, "Scratch", "Flamethrower"],
    ["Golduck", "Water", 80, 82, "Scratch", "Water Gun"],
    ["Raichu", "Electric", 60, 90, "Quick Attack", "Thunder Shock"],
    ["Ninetales", "Fire", 73, 76, "Quick Attack", "Flamethrower"],
    ["Dewgong", "Water", 90, 70, "Headbutt", "Water Gun"]
];
